name: Deploy to Firebase

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: 
      name: secrets

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    - name: Deploy to Firebase
      run: |
        cd functions/
        npm install
        echo "FIREBASE_TOKEN: $FIREBASE_TOKEN"
        firebase use default --token $FIREBASE_TOKEN
        npm run deploy
        
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}